# Simple workflow for deploying static content to GitHub Pages
# adapted from https://github.com/actions/starter-workflows/blob/main/pages/static.yml
name: Build and Deploy Most Recent PR to Pages

on:
  # Runs on pushes targeting PR that is going to merge into master
  pull_request:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages-pr
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: apt installs
        run: sudo apt update && sudo apt install -y texlive-latex-extra pdf2svg

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: pip installs
        run: pip install -r requirements.txt

      - name: Build English
        run: make html
        env:
          CREATOR_ID: ${{ secrets.CREATOR_ID }}

